[package]
name = "bitcoinvert"
version = "0.1.0"
description = "CLI tool that fetches Bitcoin exchange rates from Blockchain.info and shows conversions to other currencies/denominations"
authors = ["Gabriel Comte"]
edition = "2021"
rust-version = "1.61.0"
repository = "https://github.com/gcomte/bitcoinvert"
license = "MIT"


[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
colored = "2.0.0"
env_logger = "0.10.0"
exitcode = "1.1.2"
home-config = { version = "0.6.0", features = ["yaml"] }
log = "0.4.17"
reqwest = { version = "0.11.16", features = ["blocking", "json"] }
serde = { version = "1.0.156", features = ["derive"] }
serde_yaml = "0.9.19"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
tabled = "0.10.0"
thiserror = "1.0.40"
thousands = "0.2.0"
typetag = "0.2"
