[package]
name = "bitcoinvert"
version = "0.1.0"
description = "CLI tool that fetches Bitcoin exchange rates from Blockchain.info and shows conversions to other currencies/denominations"
authors = ["Gabriel Comte"]
edition = "2021"
rust-version = "1.61.0"
repository = "https://github.com/gcomte/bitcoinvert"
license = "MIT"


[dependencies]
async-trait = "0.1.57"
clap = { version = "3.2.18", features = ["derive"] }
env_logger = "0.9.0"
exitcode = "1.1.2"
home-config = { version = "0.4.0", features = ["yaml"] }
log = "0.4.17"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_yaml = "0.9.10"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
tokio = { version = "1.20.1", features = ["full"] }
typetag = "0.2"
