[package]
name = "bitcoinvert"
version = "0.1.3"
description = "CLI tool that fetches Bitcoin exchange rates from Blockchain.info and shows conversions to other currencies/denominations"
authors = ["Gabriel Comte"]
edition = "2021"
rust-version = "1.61.0"
repository = "https://github.com/gcomte/bitcoinvert"
license = "MIT"


[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
colored = "2.0.0"
env_logger = "0.10.0"
exitcode = "1.1.2"
home-config = { version = "0.6.0", features = ["yaml"] }
log = "0.4.20"
regex = "1.9.3"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.168", features = ["derive"] }
serde_yaml = "0.9.25"
si-unit-prefix = "1.0.0"
strum = { version = "0.25", features = ["derive"] }
strum_macros = "0.25"
tabled = "0.14.0"
thiserror = "1.0.47"
thousands = "0.2.0"
typetag = "0.2"

[dev-dependencies]
assert_cmd = "2.0.12"
